### PR TITLE
adding my name in .md file

### PR DESCRIPTION
**Pull request by slayer321**
#ISSUE-NO

### CODE REVIEW

**Review by chryzcode — CHANGES_REQUESTED** [review]
Please you gave to arrange your name alphabetically in line with the other names on the list.

Your name starts with `S`, so fix it in an alphabetical order.

Thanks

**Review by chryzcode — APPROVED** [review]
Would you love to join the community @slayer321

**Comment by slayer321** [comment]
yes

**Comment by chryzcode** [comment]
Follow the Twitter Twitter community handle https://twitter.com/ChryzHub 

You would be attended to and be guided in how to go about it.

The community is looking forward to collaborate more with you @slayer321.

Hoping to see you hangout with ChryzHub

**Comment by slayer321** [comment]
yup ..... followed you on Twitter
I have already joined your discord server  username: 0x_mantis

**Comment by Evavic44** [comment]
> yup ..... followed you on Twitter
> I have already joined your discord server  username: 0x_mantis
> 

Welcome slayer. 😎

**Pull request merged**
