### PR TITLE
docs: fixed links to be active and removed space in chryz-hub-docs fo…

### PR DESCRIPTION
**Pull request by bomotayo**
…lder and urls

#ISSUE-NO #31

#### Questions: None.

Thank you.

### CODE REVIEW

**Comment by bomotayo** [comment]
In addition i also fixed the URL for the "Docs" linkable text . It is currently linking to 
https://github.com/chryz-hub/opensource-4-everyone/tree/master/chryz-hub-resources/chryz-hub-%20docs
 instead of 
https://github.com/chryz-hub/opensource-4-everyone/tree/master/chryz-hub-resources/chryz-hub-docs
Everything should work once the space is removed in "chryz-hub-docs" folder

**Review by chryzcode — CHANGES_REQUESTED** [review]
Hmmn, sorry. The changes made here was not also correct after I reviewed the links you added--- the page was not found.

Get the right links here from this folder https://github.com/chryz-hub/opensource-4-everyone/tree/master/chryz-hub-resources/chryz-hub-%20docs  
- You would find files there

then get the links of the file and replace them with this files under the `docs` section of `chryz-hub resources` respectively

**Comment by bomotayo** [comment]
Hi thank you for the feedback. 
They are not working yet because in your current URL the space in chryz-hub- docs is being converted to the URL encoding %20 i.e chryz-hub-%20docs.

If you remove the space before “docs” in the folder name chryz-hub-docs it gets rid of %20 from appearing in all your links. I tested it after removing them in my branch and it worked. 

If you don’t mind the %20 urls I can quickly fix but wanted to bring it to your attention first.

Regards

**Comment by bomotayo** [comment]
Attached is a screenshot of where the space should be removed in the folder name to get all the updated links to work. Unfortunately I was not able to update the folder name from my end.

Screen Shot 2021-03-17 at 9 34 53 AM

Thank you.

**Review by chryzcode — APPROVED** [review]
Oh, thanks!
That was a mistake, I already made the rightful changes.

So we are good to go🚀
Want to know if you would love to join our community!

**Comment by bomotayo** [comment]
No problem! Thank you for the opportunity to contribute and yes i would like to join your community.

**Comment by chryzcode** [comment]
> No problem! Thank you for the opportunity to contribute and yes i would like to join your community.

Join our
<ul><li><a href="https://discord.gg/c6RhGwcP5b">Discord server</a>where we collaborate and discuss more</li><li><a href="https://youtube.com/channel/UCxro6LYOp3pmmuWDPMg-p1Q">New Youtube channel</a> by subscribing to know more on opensource and programming </li><li><a href="https://twitter.com/ChryzHub">Twitter</a></li><li>And lastly our <a href="https://github.com/chryz-hub">GitHub organization</a> by raising an <a href="https://github.com/chryz-hub/chryz-hub.github.io/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.md&title=Please+invite+me+to+the+GitHub+Community+Organization">invitational issue </a>and after raising the issue wait to get messages from a bot because it would direct you on how to complete the process</li></ul>

If you have any question, feel free to ask
- You can also check the vision of the community https://github.com/chryz-hub/chryz-hub.github.io/blob/master/vision.md

**Pull request merged**
