### PR TITLE
Update My-PR-Contribution-Practice.md

### PR DESCRIPTION
**Pull request by SyedZawwarAhmed**
#ISSUE-NO

### CODE REVIEW

**Review by chryzcode — APPROVED** [review]
Congratulations on your pull request🥳🎉.

Changes added .... Changes approved! 🚀

If you would love to join the community, please let me know!

**Comment by chryzcode** [comment]
I actually needed to correct some stuffs 😅

The arrangement was kind 'a odd.

But I already did it and merged it

**Comment by SyedZawwarAhmed** [comment]
> Congratulations on your pull request🥳🎉.
> 
> Changes added .... Changes approved! 🚀
> 
> If you would love to join the community, please let me know!

Yeah sure! I want to join the community.

**Comment by chryzcode** [comment]
Okay, just follow the community Twitter handle. You would be directed on how to go about it.

Link https://twitter.com/ChryzHub

**Pull request merged**
