### PR TITLE
Update Readme file

### PR DESCRIPTION
**Pull request by Shubham-Vishwakarma**

### CODE REVIEW

**Review by chryzcode — COMMENTED** [review]
Ok, the link is correct, but I feel this is way more  complex than the one present there before. Check the difference!

**Comment by chryzcode** [comment]
Hello, I sent you an invitation to be a member in our community, It's been a while now. I don't know if it has expired but check your mail to accept if it is still valid.

If not let me know that's if you are willing to be one of us!

**Comment by Shubham-Vishwakarma** [comment]
@chryzcodez 
Thanks for invitation.
But I won't be joining.
I have just started exploring GitHub
I would like to contribute to all your project wherever I can, but won't join it

**Comment by chryzcode** [comment]
ok, no issues. You are welcome to contribute to all our projects!

**Pull request closed without merging**
