### PR TITLE
added lola's contribution

### PR DESCRIPTION
**Pull request by Lhorla001**
#ISSUE-NO

#### Description of Task to be completed?
Added lola's bio to contributing practice md

### CODE REVIEW

**Review by chryzcode — CHANGES_REQUESTED** [review]
Hi @Lhorla, kindly add your details to the list in alphabetical order.

**Comment by Lhorla001** [comment]
> Hi @Lhorla, kindly add your details to the list in alphabetical order.

I've made the change @chryzcode

**Review by chryzcode — APPROVED** [review]
LGTM 👍

**Comment by Lhorla001** [comment]
> LGTM 👍

Thank you

**Pull request merged**
