### PR TITLE
Addition Of Open Source Blogs

### PR DESCRIPTION
**Pull request by Mannuel25**
I added a few open source blogs

### CODE REVIEW

**Review by Evavic44 — APPROVED** [review]

**Review by Evavic44 — CHANGES_REQUESTED** [review]
I suggest links should have an `_blank` attribute so when clicked will open up links in a new tab.

**Comment by Mannuel25** [comment]
> I suggest links should have an `_blank` attribute so when clicked will open up links in a new tab.

Oh,okay. Imma work on that, thanks.

**Comment by Mannuel25** [comment]
@Evavic44, I made a few research and I got to know that it isn't possible to add the attribute.

references: https://stackoverflow.com/questions/41915571/open-link-in-new-tab-with-github-markdown-using-target-blank

https://github.community/t/cant-get-links-to-open-in-new-tab-bis/2326

**Comment by chryzcode** [comment]
> @Evavic44, I made a few research and I got to know that it isn't possible to add the attribute.
> 
> references: https://stackoverflow.com/questions/41915571/open-link-in-new-tab-with-github-markdown-using-target-blank
> 
> https://github.community/t/cant-get-links-to-open-in-new-tab-bis/2326

Yeah that's true. It doesn't work on markdown files, I think.

**Comment by Mannuel25** [comment]
> > @Evavic44, I made a few research and I got to know that it isn't possible to add the attribute.
> > references: https://stackoverflow.com/questions/41915571/open-link-in-new-tab-with-github-markdown-using-target-blank
> > https://github.community/t/cant-get-links-to-open-in-new-tab-bis/2326
> 
> Yeah that's true. It doesn't work on markdown files, I think.

yeahh

**Review by chryzcode — APPROVED** [review]
LGTM👍

**Comment by Evavic44** [comment]
> @Evavic44, I made a few research and I got to know that it isn't possible to add the attribute.
> 
> references: https://stackoverflow.com/questions/41915571/open-link-in-new-tab-with-github-markdown-using-target-blank
> 
> https://github.community/t/cant-get-links-to-open-in-new-tab-bis/2326

Just finding out for the first time. Wow, seriously!?

**Pull request merged**
